#!/bin/bash
pip install --upgrade pip
pip install --no-cache-dir voila ipywidgets==7.7.1 pandas==1.5.3 numpy==1.24.1 notebook jupyter
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
